Create Login Activity
DankIdeaCentral/migrate-app pull request #44
Opened 2016-10-06 20:08 UTC by basimr

The authentication is working, but it's "primitive". I'll still have to:
- do some work to make it better
- clean up the code

I won't be closing the LoginActivity issue until I finish these two things.

2016-10-06 21:06 UTC, srowhani requested changes
Looks good :+1:

2016-10-06 21:06 UTC, srowhani commented on app/src/main/java/com/dankideacentral/dic/ConstantValues.java
> +public class ConstantValues {
Instead of a ConstantValues class, I believe it would be considered better practice to have resources in the `strings.xml` file.

2016-10-06 21:47 UTC, basimr commented on app/src/main/java/com/dankideacentral/dic/ConstantValues.java
> +public class ConstantValues {
I was initially thinking of making second pull request to fix that issue, but perhaps it's better for me to commit to this feature until I'm officially done with the LoginActivity issue.

2016-10-06 21:55 UTC, basimr commented
@srowhani @zandermax @ermel272: is it better practice to group all the authentication-related class files under com.dankideacentral.dic.authentication?

2016-10-06 22:46 UTC, srowhani commented
Good call

2016-10-07 05:21 UTC, srowhani approved these changes
Good stuff! Going to merge

2016-10-07 05:21 UTC, merged